root = "."
tmp_dir = "tmp_recorder"

[build]
entrypoint = "/bin/true"
cmd = "make build-recorder-win"
delay = 1000
exclude_dir = [
  "cmd/server",
  "internal/server",
  "cmd/worker",
  "internal/worker",
  "ui",
  "tmp_worker",
  "tmp_server",
  "screenshots",
  "dist",
]
include_ext = ["go"]
kill_delay = "0s"
log = "logs/build-recorder-errors.log"

[color]
main = "cyan"
watcher = "cyan"
build = "cyan"
runner = "cyan"

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
