root = "."
tmp_dir = "tmp_worker"

[build]
entrypoint = "dist/worker"
cmd = "make build-worker"
delay = 1000
exclude_dir = [
  "cmd/server",
  "internal/server",
  "cmd/recorder",
  "internal/recorder",
  "ui",
  "tmp_server",
  "tmp_recorder",
  "screenshots",
  "dist",
]
include_ext = ["go"]
kill_delay = "0s"
log = "logs/build-worker-errors.log"

[color]
main = "green"
watcher = "green"
build = "green"
runner = "green"

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
