root = "."
tmp_dir = "tmp_server"

[build]
entrypoint = "dist/server"
cmd = "make build-server"
delay = 1000
exclude_dir = [
  "cmd/worker",
  "internal/worker",
  "cmd/recorder",
  "internal/recorder",
  "ui",
  "tmp_worker",
  "tmp_recorder",
  "screenshots",
  "dist",
]
include_ext = ["go"]
kill_delay = "0s"
log = "logs/build-server-errors.log"

[color]
main = "yellow"
watcher = "yellow"
build = "yellow"
runner = "yellow"

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
