services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: fragtape
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 12
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    build:
      context: .
      dockerfile: docker/server-dev.Dockerfile
    container_name: backend
    command: sh -c "go mod download && air -c .air.server.toml"
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/ui
      - go_packages:/go/pkg/mod
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  frontend:
    build:
      context: ui
      dockerfile: dev.Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./ui:/app
      - frontend_packages:/app/node_modules
    depends_on:
      - backend

  worker:
    build:
      context: .
      dockerfile: docker/worker-dev.Dockerfile
    container_name: worker
    command: sh -c "go mod download && air -c .air.worker.toml"
    volumes:
      - .:/app
      - /app/ui
      - go_packages:/go/pkg/mod
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  recorder-manager:
    build:
      context: .
      dockerfile: docker/recorder-dev.Dockerfile
    container_name: recorder-m
    command: sh -c "/app/docker/recorder-dev-entrypoint.sh"
    ports:
      - "15432:15432"
      - "19000:19000"
    volumes:
      - .:/app
      - /app/ui
      - go_packages:/go/pkg/mod
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  recorder:
    image: dockurr/windows
    container_name: recorder
    environment:
      VERSION: 11
      USERNAME: Fragtape
      PASSWORD: admin
      DISK_SIZE: ${RECORDER_DISK_SIZE:-128G}
      RAM_SIZE: ${RECORDER_RAM_SIZE:-8G}
      CPU_CORES: ${RECORDER_CPU_CORES:-8}
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - recorder_data:/storage
      - ./config:/shared/recorder/config
      - ./logs:/shared/recorder/logs
      - ./dist/:/shared/recorder/dist
      - ./.env:/shared/recorder/.env
      - ./internal/recorder/capture/dummydata:/shared/recorder/internal/recorder/capture/dummydata
      - ./docker/recorder-dev-oem:/oem
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  db_data:
  minio_data:
  go_packages:
  frontend_packages:
  recorder_data:
