app:
  name:

server:
  api:
    host:
    port: 3001

  auth:
    steam:
      api_key:
      callback_url: http://localhost:3001/api/auth/callback/steam
    redirect_url: http://localhost:3000

  logger:
    file:

  db:
    host:
    port:
    database:
    user:
    password:

  minio:
    bucket:
    endpoint:
    secure:
    username:
    password:

worker:
  parser:
    interval_s: 10
    concurrent: 1
    positions_per_second:
    positions_min_distance:

  finalizer:
    interval_s: 10
    concurrent: 1

  logger:
    file:

  db:
    host:
    port:
    database:
    user:
    password:

  minio:
    bucket:
    endpoint:
    secure:
    username:
    password:

recorder:
  interval_s: 10
  dummy_data: true
  hlae_path: "C:\\Program Files (x86)\\HLAE"
  cs2_path: "C:\\Program Files (x86)\\Steam\\SteamApps\\common\\Counter-Strike Global Offensive"

  logger:
    file: recorder

  db:
    host:
    port:
    database:
    user:
    password:

  minio:
    bucket:
    endpoint:
    secure:
    username:
    password:
