app:
  name:

server:
  api:
    host:
    port: 3001

  auth:
    steam:
      api_key:
      callback_url: http://localhost:3001/api/auth/callback/steam
    redirect_url: http://localhost:3000

  db:
    host:
    port:
    database:
    user:
    password:

  minio:
    bucket:
    endpoint:
    secure:
    username:
    password:

worker:
  parser:
    interval_s:
    concurrent:
    positions_per_second:
    positions_min_distance:

  finalizer:
    interval_s:
    concurrent:

  db:
    host:
    port:
    database:
    user:
    password:

  minio:
    bucket:
    endpoint:
    secure:
    username:
    password:

recorder:
  interval_s:
  dummy_data: true

  db:
    host:
    port:
    database:
    user:
    password:

  minio:
    bucket:
    endpoint:
    secure:
    username:
    password:
