app:
  name: fragtape

server:
  api:
    host: 0.0.0.0
    port: 8000

  auth:
    steam:
      api_key:
      callback_url:

  logger:
    file: server

  db:
    host: db
    port: 5432
    database: fragtape
    user: postgres
    password: postgres

  minio:
    bucket: fragtape
    endpoint: minio:9000
    secure: false
    username: minio
    password: miniominio

worker:
  parser:
    interval_s: 60
    concurrent: 8
    positions_per_second: 4
    positions_min_distance: 10

  finalizer:
    interval_s: 60
    concurrent: 8

  logger:
    file: worker

  db:
    host: db
    port: 5432
    database: fragtape
    user: postgres
    password: postgres

  minio:
    bucket: fragtape
    endpoint: minio:9000
    secure: false
    username: minio
    password: miniominio

recorder:
  interval_s: 60
  dummy_data: false

  logger:
    file: recorder

  db:
    host: db
    port: 5432
    database: fragtape
    user: postgres
    password: postgres

  minio:
    bucket: fragtape
    endpoint: minio:9000
    secure: false
    username: minio
    password: miniominio
