app:
  name: fragtape

server:
  api:
    host: 0.0.0.0
    port: 8000

  auth:
    steam:
      api_key:
      callback_url:

  db:
    host: db
    port: 5432
    database: fragtape
    user: postgres
    password: postgres

  minio:
    bucket: fragtape
    endpoint: minio:9000
    secure: false
    username: minio
    password: miniominio

worker:
  interval_s:
    parser: 60
    finalizer: 60
  concurrent:
    parser: 8
    finalizer: 8

  db:
    host: db
    port: 5432
    database: fragtape
    user: postgres
    password: postgres

  minio:
    bucket: fragtape
    endpoint: minio:9000
    secure: false
    username: minio
    password: miniominio

recorder:
  interval_s: 60
  dummy_data: false

  db:
    host: db
    port: 5432
    database: fragtape
    user: postgres
    password: postgres

  minio:
    bucket: fragtape
    endpoint: minio:9000
    secure: false
    username: minio
    password: miniominio
